version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.9.0

jobs:
  publish-package:
    <<: *defaults
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Authenticate with registry
          command: |
            echo "registry=https://piratecat.jfrog.io/artifactory/api/npm/npm/" > ~/repo/.npmrc
            echo "_auth = $JFROG_HASH" > ~/repo/.npmrc
            echo "email = $JFROG_EMAIL" >> ~/repo/.npmrc
            echo "always-auth = true"
      - run:
          name: Publish package
          command: npm publish

workflows:
  release-package:
    jobs:
      - publish-package:
          context: jfrog-artifactory
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/