version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.9.0

jobs:
  publish-github-package:
    <<: *defaults
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Authenticate with registiry
          command: |
            echo "registry=https://npm.pkg.github.com/PirateCatStudios" > ~/repo/.npmrc
            echo "//npm.pkg.github.com/:_authToken={$GITHUB_PACKAGES_TOKEN}" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  release-package:
    jobs:
      - publish-github-package:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/